name: Build Flink SQL runner custom image
on:
  push:
    tags:
      - release/*
jobs:
  build-release-jar:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
        with:
          tagRegex: "release/(.*)"
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .tool-versions
      - name: Build with Maven
        run: |
          mvn clean package
        working-directory: .
      - name: Rename version
        run: |
          mv target/flink-sql-runner-*.jar target/flink-sql-runner-${{ steps.tagName.outputs.tag }}.jar
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: | 
            target/flink-sql-runner-${{ steps.tagName.outputs.tag }}.jar
